# Generated by Django 4.1.5 on 2023-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_price_product_narx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='narx',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000000),
            preserve_default=False,
        ),
    ]
